/vis/open VtkOffscreen
/vis/viewer/set/autoRefresh false
/vis/verbose errors

/vis/viewer/set/style surface
/vis/viewer/set/edge true
/vis/viewer/set/auxiliaryEdge false
/vis/viewer/set/hiddenMarker true
/vis/viewer/set/background white
/vis/viewer/set/projection perspective 30
/vis/vtk/set/polyhedronPipeline tensor

/vis/drawVolume
/vis/viewer/set/viewpointThetaPhi 90 -90
/vis/viewer/set/upThetaPhi 0 0
/vis/viewer/set/rotationStyle constrainUpDirection
/vis/viewer/set/lightsMove with-camera
/vis/viewer/set/lightsVector 1 0 0
/vis/viewer/refresh
/vis/vtk/export png /Users/acsevillam/workspace/Geant4/MDSIM1/.codex-tmp/vtk_edges_test
