/control/verbose 0
/run/verbose 0

/MultiDetector1/control/SetPrimaryGeneratorType 2

/run/initialize

/gps/particle gamma
/gps/ene/type Mono
/gps/energy 1 MeV
/gps/pos/type Point
/gps/pos/centre 0 0 0 cm
/gps/direction 0 0 -1

/MultiDetector1/detectors/BB7/addGeometryTo WaterBox 0
/MultiDetector1/detectors/BB7/detectorID 0
/MultiDetector1/detectors/BB7/translateTo 0 0 -10 cm
/MultiDetector1/detectors/BB7/rotateX 0 deg

/run/beamOn 1

/MultiDetector1/detectors/BB7/removeGeometry 0

/run/beamOn 1
